//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workFlowApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_entity
    {
        public int entity_id { get; set; }
        public string entity_name { get; set; }
        public string action_name { get; set; }
        public string action_description { get; set; }
        public string entry_criteria { get; set; }
        public string exit_criteria { get; set; }
        public int entity_owner { get; set; }
        public int entity_status { get; set; }
        public int change_status { get; set; }
        public Nullable<int> workflow_id { get; set; }
    
        public virtual tbl_empoyee tbl_empoyee { get; set; }
        public virtual Work_flow_tbl Work_flow_tbl { get; set; }
    }
}
