//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workFlowApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work_flow_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Work_flow_tbl()
        {
            this.tbl_entity = new HashSet<tbl_entity>();
        }
    
        public int work_flow_id { get; set; }
        public string work_flow_name { get; set; }
        public string work_flow_description { get; set; }
        public Nullable<int> work_flow_status { get; set; }
        public Nullable<System.DateTime> work_flow_created_date { get; set; }
        public Nullable<int> work_flow_owner { get; set; }
        public Nullable<int> work_flow_created_user { get; set; }
        public string entry_criteria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_entity> tbl_entity { get; set; }
    }
}
